//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q3LogAnalyzer.LogFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogFileService.LogFileSvcSoap")]
    public interface LogFileSvcSoap {
        
        // CODEGEN: Generating message contract since element name ReadLogfileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadLogfile", ReplyAction="*")]
        Q3LogAnalyzer.LogFileService.ReadLogfileResponse ReadLogfile(Q3LogAnalyzer.LogFileService.ReadLogfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadLogfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadLogfile", Namespace="http://tempuri.org/", Order=0)]
        public Q3LogAnalyzer.LogFileService.ReadLogfileRequestBody Body;
        
        public ReadLogfileRequest() {
        }
        
        public ReadLogfileRequest(Q3LogAnalyzer.LogFileService.ReadLogfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadLogfileRequestBody {
        
        public ReadLogfileRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadLogfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadLogfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Q3LogAnalyzer.LogFileService.ReadLogfileResponseBody Body;
        
        public ReadLogfileResponse() {
        }
        
        public ReadLogfileResponse(Q3LogAnalyzer.LogFileService.ReadLogfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadLogfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ReadLogfileResult;
        
        public ReadLogfileResponseBody() {
        }
        
        public ReadLogfileResponseBody(byte[] ReadLogfileResult) {
            this.ReadLogfileResult = ReadLogfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogFileSvcSoapChannel : Q3LogAnalyzer.LogFileService.LogFileSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogFileSvcSoapClient : System.ServiceModel.ClientBase<Q3LogAnalyzer.LogFileService.LogFileSvcSoap>, Q3LogAnalyzer.LogFileService.LogFileSvcSoap {
        
        public LogFileSvcSoapClient() {
        }
        
        public LogFileSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogFileSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogFileSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogFileSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Q3LogAnalyzer.LogFileService.ReadLogfileResponse Q3LogAnalyzer.LogFileService.LogFileSvcSoap.ReadLogfile(Q3LogAnalyzer.LogFileService.ReadLogfileRequest request) {
            return base.Channel.ReadLogfile(request);
        }
        
        public byte[] ReadLogfile() {
            Q3LogAnalyzer.LogFileService.ReadLogfileRequest inValue = new Q3LogAnalyzer.LogFileService.ReadLogfileRequest();
            inValue.Body = new Q3LogAnalyzer.LogFileService.ReadLogfileRequestBody();
            Q3LogAnalyzer.LogFileService.ReadLogfileResponse retVal = ((Q3LogAnalyzer.LogFileService.LogFileSvcSoap)(this)).ReadLogfile(inValue);
            return retVal.Body.ReadLogfileResult;
        }
    }
}
